feed_list_focused_width = "25%"
article_list_focused_width = "75%"
article_list_focused_height = "40%"
article_content_focused_height = "60%"

date_format = "%d/%m/%Y %H:%M"
content_preferred_type = "markdown"
keep_articles_days = 999
sync_every_minutes = 15
startup_commands = ["sync", "focus articles"]

feed_list = [
  'query: "Today Unread" today unread',
  "feeds",
  "* categories"
]

share_targets = [
  "clipboard",
  "mpv mpv {url}"
]

[input_config.mappings]
"q" = ["quit"]
"r" = ["read", "nextunread"]
"S m" = ["share mpv"]

